# Generated by Django 4.1.3 on 2022-12-01 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActionMonstre',
            fields=[
                ('index', models.CharField(default='default', max_length=50, primary_key=True, serialize=False)),
                ('desc', models.TextField(blank=True, null=True, verbose_name='description')),
                ('nom', models.CharField(blank=True, max_length=50, null=True)),
                ('type', models.CharField(blank=True, max_length=50, null=True)),
                ('bonus_attaque', models.IntegerField(blank=True, null=True)),
                ('legendaire', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Alignement',
            fields=[
                ('nom', models.CharField(max_length=50)),
                ('index', models.CharField(default='default', max_length=50, primary_key=True, serialize=False)),
                ('desc', models.TextField(blank=True, null=True, verbose_name='description')),
                ('abreviation', models.CharField(blank=True, max_length=2, null=True)),
                ('url', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Capacite',
            fields=[
                ('nom', models.CharField(max_length=50)),
                ('index', models.CharField(default='default', max_length=50, primary_key=True, serialize=False)),
                ('desc', models.TextField(blank=True, null=True, verbose_name='description')),
                ('url', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CapaciteHistorique',
            fields=[
                ('nom', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('desc', models.TextField(blank=True, null=True, verbose_name='description')),
            ],
        ),
        migrations.CreateModel(
            name='CapaciteMonstre',
            fields=[
                ('nom', models.CharField(max_length=50)),
                ('index', models.CharField(default='default', max_length=50, primary_key=True, serialize=False)),
                ('desc', models.TextField(blank=True, null=True, verbose_name='description')),
                ('url', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Caracteristique',
            fields=[
                ('nom', models.CharField(max_length=50)),
                ('index', models.CharField(default='default', max_length=50, primary_key=True, serialize=False)),
                ('desc', models.TextField(blank=True, null=True, verbose_name='description')),
                ('url', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CategorieEquipement',
            fields=[
                ('nom', models.CharField(max_length=50)),
                ('index', models.CharField(default='default', max_length=50, primary_key=True, serialize=False)),
                ('desc', models.TextField(blank=True, null=True, verbose_name='description')),
                ('url', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Cible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.TextField(blank=True, null=True)),
                ('type', models.CharField(blank=True, default='créature', max_length=50, null=True)),
                ('cible', models.IntegerField(blank=True, default=1, null=True)),
                ('zone', models.BooleanField(default=False)),
                ('rayon', models.IntegerField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('nom', models.CharField(max_length=50)),
                ('index', models.CharField(default='default', max_length=50, primary_key=True, serialize=False)),
                ('desc', models.TextField(blank=True, null=True, verbose_name='description')),
                ('pv', models.IntegerField(default=8)),
                ('url_niveau', models.CharField(blank=True, max_length=50, null=True)),
                ('url', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ClasseArmure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base', models.IntegerField(default=11)),
                ('dex_bonus', models.BooleanField(default=True)),
                ('max_bonus', models.IntegerField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Competence',
            fields=[
                ('nom', models.CharField(max_length=50)),
                ('index', models.CharField(default='default', max_length=50, primary_key=True, serialize=False)),
                ('desc', models.TextField(blank=True, null=True, verbose_name='description')),
                ('url', models.CharField(blank=True, max_length=50, null=True)),
                ('caracteristique', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='competences', to='data.caracteristique')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Composante',
            fields=[
                ('index', models.CharField(max_length=1, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=10, null=True)),
                ('consomme', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='DefautHistorique',
            fields=[
                ('index', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('nom', models.CharField(blank=True, max_length=50, null=True)),
                ('desc', models.TextField(blank=True, null=True, verbose_name='description')),
            ],
        ),
        migrations.CreateModel(
            name='Degat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bonus', models.IntegerField(default=0)),
                ('de', models.CharField(default='1d6', max_length=50, verbose_name='dé de dégat')),
            ],
        ),
        migrations.CreateModel(
            name='DomaineHistorique',
            fields=[
                ('index', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('nom', models.CharField(blank=True, max_length=50, null=True)),
                ('desc', models.TextField(blank=True, null=True, verbose_name='description')),
            ],
        ),
        migrations.CreateModel(
            name='EcoleMagie',
            fields=[
                ('nom', models.CharField(max_length=50)),
                ('index', models.CharField(default='default', max_length=50, primary_key=True, serialize=False)),
                ('desc', models.TextField(blank=True, null=True, verbose_name='description')),
                ('url', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EmplacementSort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_connu', models.IntegerField(blank=True, default=None, null=True)),
                ('nv_0', models.IntegerField(default=0)),
                ('nv_1', models.IntegerField(default=0)),
                ('nv_2', models.IntegerField(default=0)),
                ('nv_3', models.IntegerField(default=0)),
                ('nv_4', models.IntegerField(default=0)),
                ('nv_5', models.IntegerField(default=0)),
                ('nv_6', models.IntegerField(default=0)),
                ('nv_7', models.IntegerField(default=0)),
                ('nv_8', models.IntegerField(default=0)),
                ('nv_9', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Equipement',
            fields=[
                ('nom', models.CharField(max_length=50)),
                ('index', models.CharField(default='default', max_length=50, primary_key=True, serialize=False)),
                ('desc', models.TextField(blank=True, null=True, verbose_name='description')),
                ('poids', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('url', models.CharField(blank=True, max_length=50, null=True)),
                ('categorie_equipement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data.categorieequipement')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Etat',
            fields=[
                ('nom', models.CharField(max_length=50)),
                ('index', models.CharField(default='default', max_length=50, primary_key=True, serialize=False)),
                ('desc', models.TextField(blank=True, null=True, verbose_name='description')),
                ('url', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Historique',
            fields=[
                ('nom', models.CharField(max_length=50)),
                ('index', models.CharField(default='default', max_length=50, primary_key=True, serialize=False)),
                ('desc', models.TextField(blank=True, null=True, verbose_name='description')),
                ('url', models.CharField(blank=True, max_length=50, null=True)),
                ('competences', models.ManyToManyField(blank=True, to='data.competence')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IdealHistorique',
            fields=[
                ('index', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('nom', models.CharField(blank=True, max_length=50, null=True)),
                ('desc', models.TextField(blank=True, null=True, verbose_name='description')),
            ],
        ),
        migrations.CreateModel(
            name='Info',
            fields=[
                ('nom', models.CharField(max_length=50)),
                ('index', models.CharField(default='default', max_length=50, primary_key=True, serialize=False)),
                ('desc', models.TextField(blank=True, null=True, verbose_name='description')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='JetDeSauvegarde',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(null=True)),
                ('caracteristique', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='JdS', to='data.caracteristique')),
            ],
        ),
        migrations.CreateModel(
            name='Langue',
            fields=[
                ('nom', models.CharField(max_length=50)),
                ('index', models.CharField(default='default', max_length=50, primary_key=True, serialize=False)),
                ('desc', models.TextField(blank=True, null=True, verbose_name='description')),
                ('type', models.CharField(blank=True, choices=[('standard', 'standard'), ('exotic', 'exotic')], max_length=10, null=True)),
                ('url', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LienHistorique',
            fields=[
                ('index', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('nom', models.CharField(blank=True, max_length=50, null=True)),
                ('desc', models.TextField(blank=True, null=True, verbose_name='description')),
            ],
        ),
        migrations.CreateModel(
            name='Maitrise',
            fields=[
                ('nom', models.CharField(max_length=50)),
                ('index', models.CharField(default='default', max_length=50, primary_key=True, serialize=False)),
                ('desc', models.TextField(blank=True, null=True, verbose_name='description')),
                ('url', models.CharField(blank=True, max_length=50, null=True)),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data.categorieequipement')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Monaie',
            fields=[
                ('nom', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('desc', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Monstre',
            fields=[
                ('nom', models.CharField(max_length=50)),
                ('index', models.CharField(default='default', max_length=50, primary_key=True, serialize=False)),
                ('desc', models.TextField(blank=True, null=True, verbose_name='description')),
                ('type', models.CharField(blank=True, max_length=50, null=True)),
                ('classe_armure', models.IntegerField(blank=True, null=True)),
                ('pv', models.IntegerField(blank=True, null=True)),
                ('de_pv', models.CharField(blank=True, max_length=50, null=True)),
                ('puissance', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('xp', models.IntegerField(blank=True, null=True)),
                ('bonus_maitrise', models.IntegerField(blank=True, null=True)),
                ('url', models.CharField(blank=True, max_length=50, null=True)),
                ('JdS', models.ManyToManyField(blank=True, related_name='JdS_monstre', to='data.jetdesauvegarde')),
                ('actions', models.ManyToManyField(blank=True, related_name='monstre', to='data.actionmonstre')),
                ('alignement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Monstre', to='data.alignement')),
                ('capacite_monstre', models.ManyToManyField(blank=True, related_name='monstre', to='data.capacitemonstre')),
                ('competences', models.ManyToManyField(blank=True, related_name='monstre', to='data.competence')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Niveau',
            fields=[
                ('nom', models.CharField(max_length=50)),
                ('index', models.CharField(default='default', max_length=50, primary_key=True, serialize=False)),
                ('desc', models.TextField(blank=True, null=True, verbose_name='description')),
                ('niveau', models.IntegerField(default=1)),
                ('bonus_caracteristique', models.IntegerField(default=0)),
                ('bonus_maitrise', models.IntegerField(default=2)),
                ('capacite', models.ManyToManyField(blank=True, related_name='niveau', to='data.capacite')),
                ('emplacements_sorts', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='niveau', to='data.emplacementsort')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OptionsMaitrise',
            fields=[
                ('nom', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('desc', models.TextField(blank=True, null=True, verbose_name='description')),
                ('nb', models.IntegerField(default=1, verbose_name='nombre de choix')),
                ('options', models.ManyToManyField(blank=True, to='data.maitrise')),
            ],
        ),
        migrations.CreateModel(
            name='Periode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.IntegerField(default=1)),
                ('mesure', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Portee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min', models.FloatField(blank=True, null=True)),
                ('max', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Prerequis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logique', models.CharField(blank=True, choices=[('ou', 'ou'), ('et', 'et')], max_length=2, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PrerequisMagie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProprieteArme',
            fields=[
                ('nom', models.CharField(max_length=50)),
                ('index', models.CharField(default='default', max_length=50, primary_key=True, serialize=False)),
                ('desc', models.TextField(blank=True, null=True, verbose_name='description')),
                ('url', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('nom', models.CharField(max_length=50)),
                ('index', models.CharField(default='default', max_length=50, primary_key=True, serialize=False)),
                ('desc', models.TextField(blank=True, null=True, verbose_name='description')),
                ('vitesse', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('taille_details', models.TextField(blank=True, null=True)),
                ('langues_desc', models.TextField(blank=True, null=True)),
                ('url', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RaceTypique',
            fields=[
                ('nom', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Regle',
            fields=[
                ('nom', models.CharField(max_length=50)),
                ('index', models.CharField(default='default', max_length=50, primary_key=True, serialize=False)),
                ('desc', models.TextField(blank=True, null=True, verbose_name='description')),
                ('url', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SensMonstre',
            fields=[
                ('nom', models.CharField(max_length=50)),
                ('index', models.CharField(default='default', max_length=50, primary_key=True, serialize=False)),
                ('desc', models.TextField(blank=True, null=True, verbose_name='description')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Sort',
            fields=[
                ('nom', models.CharField(max_length=50)),
                ('index', models.CharField(default='default', max_length=50, primary_key=True, serialize=False)),
                ('desc', models.TextField(blank=True, null=True, verbose_name='description')),
                ('niveau', models.IntegerField(default=1)),
                ('rituel', models.BooleanField(default=False)),
                ('concentration', models.BooleanField(default=False)),
                ('url', models.CharField(blank=True, max_length=50, null=True)),
                ('cible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sort', to='data.cible')),
                ('composantes', models.ManyToManyField(blank=True, to='data.composante')),
                ('duree', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='duree_sort', to='data.periode')),
                ('ecole', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sort', to='data.ecolemagie')),
                ('jets_sauvegardes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sort', to='data.caracteristique')),
                ('portee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data.portee')),
                ('temps_incantation', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='temps_incantation', to='data.periode')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SousRace',
            fields=[
                ('nom', models.CharField(max_length=50)),
                ('index', models.CharField(default='default', max_length=50, primary_key=True, serialize=False)),
                ('desc', models.TextField(blank=True, null=True, verbose_name='description')),
                ('url', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Specifique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Taille',
            fields=[
                ('nom', models.CharField(max_length=50)),
                ('index', models.CharField(default='default', max_length=50, primary_key=True, serialize=False)),
                ('desc', models.TextField(blank=True, null=True, verbose_name='description')),
                ('abreviation', models.CharField(blank=True, max_length=2, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Trait',
            fields=[
                ('nom', models.CharField(max_length=50)),
                ('index', models.CharField(default='default', max_length=50, primary_key=True, serialize=False)),
                ('desc', models.TextField(blank=True, null=True, verbose_name='description')),
                ('url', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TraitHistorique',
            fields=[
                ('index', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('nom', models.CharField(blank=True, max_length=50, null=True)),
                ('desc', models.TextField(blank=True, null=True, verbose_name='description')),
            ],
        ),
        migrations.CreateModel(
            name='TypeDegat',
            fields=[
                ('nom', models.CharField(max_length=50)),
                ('index', models.CharField(default='default', max_length=50, primary_key=True, serialize=False)),
                ('desc', models.TextField(blank=True, null=True, verbose_name='description')),
                ('url', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Vitesse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marche', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('nage', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('vol', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('rampe', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('escalade', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DegatSort',
            fields=[
                ('degat_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='data.degat')),
                ('desc', models.TextField(blank=True, null=True)),
                ('par_niveau', models.BooleanField(default=False, verbose_name='dégâts/niveau')),
                ('JdS_condition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='degat_de_sort', to='data.caracteristique')),
            ],
            bases=('data.degat',),
        ),
        migrations.CreateModel(
            name='Epuisement',
            fields=[
                ('etat_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='data.etat')),
                ('niveau', models.IntegerField(default=1)),
                ('effet', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('data.etat',),
        ),
        migrations.CreateModel(
            name='EquipementAventurier',
            fields=[
                ('equipement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='data.equipement')),
                ('categorie', models.CharField(blank=True, max_length=50, null=True, verbose_name="categorie d'equipement")),
            ],
            options={
                'abstract': False,
            },
            bases=('data.equipement',),
        ),
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('equipement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='data.equipement')),
                ('categorie', models.CharField(blank=True, max_length=50, null=True, verbose_name="categorie d'instrument")),
            ],
            options={
                'abstract': False,
            },
            bases=('data.equipement',),
        ),
        migrations.CreateModel(
            name='Kit',
            fields=[
                ('equipement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='data.equipement')),
                ('categorie', models.CharField(blank=True, max_length=50, null=True, verbose_name='categorie de kit')),
            ],
            options={
                'abstract': False,
            },
            bases=('data.equipement',),
        ),
        migrations.CreateModel(
            name='Outil',
            fields=[
                ('equipement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='data.equipement')),
                ('categorie', models.CharField(blank=True, max_length=50, null=True, verbose_name="categorie d'outil")),
            ],
            options={
                'abstract': False,
            },
            bases=('data.equipement',),
        ),
        migrations.CreateModel(
            name='PrerequisCaracteristique',
            fields=[
                ('prerequis_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='data.prerequis')),
            ],
            bases=('data.prerequis',),
        ),
        migrations.CreateModel(
            name='Vehicule',
            fields=[
                ('equipement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='data.equipement')),
                ('categorie', models.CharField(blank=True, max_length=50, null=True, verbose_name='categorie de véhicule')),
                ('capacité', models.IntegerField(blank=True, null=True)),
                ('vitesse', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('data.equipement',),
        ),
        migrations.CreateModel(
            name='ValeurCaracteristique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valeur', models.IntegerField(default=1)),
                ('caracteristique', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='valeur_caract', to='data.caracteristique')),
                ('monstre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='valeur_caract1', to='data.monstre')),
                ('race', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='valeur_caract', to='data.race')),
                ('sous_race', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='valeur_caract', to='data.sousrace')),
                ('prerequis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='valeur_caract', to='data.prerequiscaracteristique')),
            ],
        ),
        migrations.AddField(
            model_name='sousrace',
            name='bonus_caracteristique',
            field=models.ManyToManyField(blank=True, through='data.ValeurCaracteristique', to='data.caracteristique'),
        ),
        migrations.AddField(
            model_name='sousrace',
            name='langues',
            field=models.ManyToManyField(blank=True, related_name='sous_race', to='data.langue'),
        ),
        migrations.AddField(
            model_name='sousrace',
            name='maitrises_depart',
            field=models.ManyToManyField(blank=True, related_name='sous_race', to='data.maitrise'),
        ),
        migrations.AddField(
            model_name='sousrace',
            name='race',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sous_race', to='data.race'),
        ),
        migrations.AddField(
            model_name='sousrace',
            name='traits',
            field=models.ManyToManyField(blank=True, related_name='sous_race', to='data.trait'),
        ),
        migrations.CreateModel(
            name='SousClasse',
            fields=[
                ('nom', models.CharField(max_length=50)),
                ('index', models.CharField(default='default', max_length=50, primary_key=True, serialize=False)),
                ('desc', models.TextField(blank=True, null=True, verbose_name='description')),
                ('type_option', models.CharField(blank=True, max_length=50, null=True)),
                ('url_niveau', models.CharField(blank=True, max_length=50, null=True)),
                ('url', models.CharField(blank=True, max_length=50, null=True)),
                ('classe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sous_classe', to='data.classe')),
                ('sorts', models.ManyToManyField(blank=True, related_name='sous_classe', to='data.sort')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RegleSousSection',
            fields=[
                ('nom', models.CharField(max_length=50)),
                ('index', models.CharField(default='default', max_length=50, primary_key=True, serialize=False)),
                ('desc', models.TextField(blank=True, null=True, verbose_name='description')),
                ('url', models.CharField(blank=True, max_length=50, null=True)),
                ('regle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sous_section', to='data.regle')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='race',
            name='bonus_caracteristique',
            field=models.ManyToManyField(blank=True, through='data.ValeurCaracteristique', to='data.caracteristique'),
        ),
        migrations.AddField(
            model_name='race',
            name='langues',
            field=models.ManyToManyField(blank=True, related_name='race', to='data.langue'),
        ),
        migrations.AddField(
            model_name='race',
            name='maitrises_depart',
            field=models.ManyToManyField(blank=True, related_name='race', to='data.maitrise'),
        ),
        migrations.AddField(
            model_name='race',
            name='maitrises_option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='race', to='data.optionsmaitrise'),
        ),
        migrations.AddField(
            model_name='race',
            name='taille',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Race', to='data.taille'),
        ),
        migrations.AddField(
            model_name='race',
            name='traits',
            field=models.ManyToManyField(blank=True, related_name='race', to='data.trait'),
        ),
        migrations.CreateModel(
            name='QuantiteSpecifique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.IntegerField(default=1)),
                ('niveau', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data.niveau')),
                ('specifique', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data.specifique')),
            ],
        ),
        migrations.CreateModel(
            name='QuantiteMonaie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.IntegerField(default=1)),
                ('equipement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data.equipement')),
                ('monaie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data.monaie')),
            ],
        ),
        migrations.CreateModel(
            name='QuantiteEquipement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.IntegerField(default=1)),
                ('classe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quantite_equipement', to='data.classe')),
                ('equipement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quantite_equipement', to='data.equipement')),
                ('historique', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quantite_equipement', to='data.historique')),
            ],
        ),
        migrations.CreateModel(
            name='PrerequisRace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('race', models.ManyToManyField(blank=True, to='data.race')),
            ],
        ),
        migrations.CreateModel(
            name='PrerequisMaitrise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maitrise', models.ManyToManyField(blank=True, to='data.maitrise')),
            ],
        ),
        migrations.CreateModel(
            name='Personalite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Defaut', models.ManyToManyField(blank=True, related_name='personalite', to='data.defauthistorique')),
                ('capacite', models.ManyToManyField(blank=True, related_name='personalite', to='data.capacitehistorique')),
                ('domaine', models.ManyToManyField(blank=True, related_name='personalite', to='data.domainehistorique')),
                ('historique', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='personalite', to='data.historique')),
                ('ideal', models.ManyToManyField(blank=True, related_name='personalite', to='data.idealhistorique')),
                ('lien', models.ManyToManyField(blank=True, related_name='personalite', to='data.lienhistorique')),
                ('trait', models.ManyToManyField(blank=True, related_name='personalite', to='data.traithistorique')),
            ],
        ),
        migrations.CreateModel(
            name='OptionsLangue',
            fields=[
                ('nom', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('desc', models.TextField(blank=True, null=True, verbose_name='description')),
                ('nb', models.IntegerField(default=1, verbose_name='nombre de choix')),
                ('options', models.ManyToManyField(blank=True, to='data.langue')),
            ],
        ),
        migrations.CreateModel(
            name='OptionsEquipement',
            fields=[
                ('nom', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('desc', models.TextField(blank=True, null=True, verbose_name='description')),
                ('nb', models.IntegerField(default=1, verbose_name='nombre de choix')),
                ('options', models.ManyToManyField(blank=True, to='data.equipement')),
            ],
        ),
        migrations.CreateModel(
            name='OptionsCompetence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=50, null=True)),
                ('desc', models.TextField(blank=True, null=True)),
                ('nb', models.IntegerField(default=1, verbose_name='nombre de choix')),
                ('options', models.ManyToManyField(blank=True, to='data.competence')),
            ],
        ),
        migrations.CreateModel(
            name='NiveauxClasse',
            fields=[
                ('nom', models.CharField(max_length=50)),
                ('index', models.CharField(default='default', max_length=50, primary_key=True, serialize=False)),
                ('desc', models.TextField(blank=True, null=True, verbose_name='description')),
                ('url', models.CharField(blank=True, max_length=50, null=True)),
                ('classe', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='niveau', to='data.classe')),
                ('niveaux', models.ManyToManyField(null=True, related_name='niveaux_classe', to='data.niveau')),
                ('sous_classe', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='niveau', to='data.sousclasse')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='niveau',
            name='specifique_classe',
            field=models.ManyToManyField(blank=True, through='data.QuantiteSpecifique', to='data.specifique'),
        ),
        migrations.AddField(
            model_name='monstre',
            name='immunites_degats',
            field=models.ManyToManyField(blank=True, related_name='immunite_monstre', to='data.typedegat'),
        ),
        migrations.AddField(
            model_name='monstre',
            name='immunites_etats',
            field=models.ManyToManyField(blank=True, to='data.etat'),
        ),
        migrations.AddField(
            model_name='monstre',
            name='langue',
            field=models.ManyToManyField(blank=True, related_name='monstre', to='data.langue'),
        ),
        migrations.AddField(
            model_name='monstre',
            name='resistance_degats',
            field=models.ManyToManyField(blank=True, related_name='resistance_monstre', to='data.typedegat'),
        ),
        migrations.AddField(
            model_name='monstre',
            name='sens',
            field=models.ManyToManyField(blank=True, related_name='monstre', to='data.sensmonstre'),
        ),
        migrations.AddField(
            model_name='monstre',
            name='taille',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Monstre', to='data.taille'),
        ),
        migrations.AddField(
            model_name='monstre',
            name='valeur_caracteristique',
            field=models.ManyToManyField(blank=True, related_name='valeur_monstre', through='data.ValeurCaracteristique', to='data.caracteristique'),
        ),
        migrations.AddField(
            model_name='monstre',
            name='vitesse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Monstre', to='data.vitesse'),
        ),
        migrations.AddField(
            model_name='langue',
            name='race_typiques',
            field=models.ManyToManyField(blank=True, to='data.racetypique'),
        ),
        migrations.CreateModel(
            name='Incantation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(blank=True, max_length=50, null=True)),
                ('Caracteristique', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data.caracteristique')),
                ('info', models.ManyToManyField(blank=True, to='data.info')),
            ],
        ),
        migrations.AddField(
            model_name='historique',
            name='equipements_depart',
            field=models.ManyToManyField(blank=True, related_name='historique', through='data.QuantiteEquipement', to='data.equipement'),
        ),
        migrations.AddField(
            model_name='historique',
            name='equipements_options',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data.optionsequipement'),
        ),
        migrations.AddField(
            model_name='historique',
            name='langues_options',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data.optionslangue'),
        ),
        migrations.AddField(
            model_name='historique',
            name='maitrises_depart',
            field=models.ManyToManyField(blank=True, related_name='historique', to='data.maitrise'),
        ),
        migrations.AddField(
            model_name='historique',
            name='maitrises_options',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data.optionsmaitrise'),
        ),
        migrations.AddField(
            model_name='equipement',
            name='prix',
            field=models.ManyToManyField(blank=True, through='data.QuantiteMonaie', to='data.monaie'),
        ),
        migrations.AddField(
            model_name='degat',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data.typedegat'),
        ),
        migrations.AddField(
            model_name='composante',
            name='materiel',
            field=models.ManyToManyField(blank=True, to='data.equipement'),
        ),
        migrations.AddField(
            model_name='classe',
            name='equipements_depart',
            field=models.ManyToManyField(blank=True, related_name='classe', through='data.QuantiteEquipement', to='data.equipement'),
        ),
        migrations.AddField(
            model_name='classe',
            name='equipements_options',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data.optionsequipement'),
        ),
        migrations.AddField(
            model_name='classe',
            name='incantation',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='classe', to='data.incantation'),
        ),
        migrations.AddField(
            model_name='classe',
            name='jets_sauvegardes',
            field=models.ManyToManyField(blank=True, related_name='classe', to='data.caracteristique'),
        ),
        migrations.AddField(
            model_name='classe',
            name='maitrises',
            field=models.ManyToManyField(blank=True, related_name='classe', to='data.maitrise'),
        ),
        migrations.AddField(
            model_name='classe',
            name='options_competences',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='classe', to='data.optionscompetence'),
        ),
        migrations.AddField(
            model_name='classe',
            name='options_maitrises',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data.optionsmaitrise'),
        ),
        migrations.AddField(
            model_name='classe',
            name='sorts',
            field=models.ManyToManyField(blank=True, related_name='classe', to='data.sort'),
        ),
        migrations.AddField(
            model_name='actionmonstre',
            name='cible',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='action_monstre', to='data.cible'),
        ),
        migrations.AddField(
            model_name='actionmonstre',
            name='degat',
            field=models.ManyToManyField(blank=True, related_name='action_monstre', to='data.degat'),
        ),
        migrations.AddField(
            model_name='actionmonstre',
            name='jets_sauvegardes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='action_monstre', to='data.caracteristique'),
        ),
        migrations.AddField(
            model_name='actionmonstre',
            name='portee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data.portee'),
        ),
        migrations.AddField(
            model_name='sort',
            name='degats',
            field=models.ManyToManyField(to='data.degatsort'),
        ),
        migrations.AddField(
            model_name='prerequiscaracteristique',
            name='caracteristique',
            field=models.ManyToManyField(blank=True, related_name='prerequis', through='data.ValeurCaracteristique', to='data.caracteristique'),
        ),
        migrations.CreateModel(
            name='PackEquipement',
            fields=[
                ('equipement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='data.equipement')),
                ('lettre', models.CharField(blank=True, max_length=50, null=True)),
                ('contenu', models.ManyToManyField(blank=True, related_name='pack', to='data.equipement')),
            ],
            options={
                'abstract': False,
            },
            bases=('data.equipement',),
        ),
        migrations.CreateModel(
            name='Multiclasse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classe', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='data.classe')),
                ('maitrise', models.ManyToManyField(to='data.maitrise')),
                ('prerequis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data.prerequiscaracteristique')),
            ],
        ),
        migrations.CreateModel(
            name='Don',
            fields=[
                ('nom', models.CharField(max_length=50)),
                ('index', models.CharField(default='default', max_length=50, primary_key=True, serialize=False)),
                ('desc', models.TextField(blank=True, null=True, verbose_name='description')),
                ('url', models.CharField(blank=True, max_length=50, null=True)),
                ('prerequis_magie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='don', to='data.prerequismagie')),
                ('prerequis_maitrise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='don', to='data.prerequismaitrise')),
                ('prerequis_race', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='don', to='data.prerequisrace')),
                ('prerequis_caracteristique', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='don', to='data.prerequiscaracteristique')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Armure',
            fields=[
                ('equipement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='data.equipement')),
                ('categorie', models.CharField(blank=True, max_length=50, null=True, verbose_name="categorie d'armure")),
                ('force_min', models.IntegerField(default=0)),
                ('desaventage_discretion', models.BooleanField(default=False)),
                ('classeArmure', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data.classearmure')),
            ],
            options={
                'abstract': False,
            },
            bases=('data.equipement',),
        ),
        migrations.CreateModel(
            name='Arme',
            fields=[
                ('equipement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='data.equipement')),
                ('categorie', models.CharField(blank=True, choices=[('Arme courante', 'Arme courante'), ('Arme de guerre', 'Arme de guerre')], max_length=50, null=True, verbose_name="categorie d'arme")),
                ('type_portee', models.CharField(blank=True, choices=[('corps à corps', 'corps à corps'), ('distance', 'distance')], max_length=50, null=True, verbose_name='type de portée')),
                ('categorie_portee', models.CharField(blank=True, max_length=50, null=True)),
                ('special', models.TextField(blank=True, null=True)),
                ('degat_deux_mains', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='degat2mains', to='data.degat')),
                ('degat_une_main', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='degat1main', to='data.degat')),
                ('portee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data.portee')),
                ('propriete', models.ManyToManyField(blank=True, to='data.proprietearme')),
            ],
            options={
                'abstract': False,
            },
            bases=('data.equipement',),
        ),
    ]
