# Generated by Django 4.1.3 on 2022-11-27 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BonusCaracteristique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valeur', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Caracteristique',
            fields=[
                ('id', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=20, null=True)),
                ('desc', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Choix',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('desc', models.TextField(null=True)),
                ('dv', models.IntegerField(null=True)),
                ('nb_competences', models.IntegerField(default=2)),
            ],
        ),
        migrations.CreateModel(
            name='Competence',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('desc', models.TextField(null=True)),
                ('caracteristique', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='competences', to='data.caracteristique')),
            ],
        ),
        migrations.CreateModel(
            name='Equipement',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('desc', models.TextField(blank=True, null=True)),
                ('prix', models.FloatField(blank=True, null=True)),
                ('poids', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Historique',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('desc', models.TextField(null=True)),
                ('po', models.IntegerField(blank=True, null=True)),
                ('competences', models.ManyToManyField(related_name='historiques', to='data.competence')),
            ],
        ),
        migrations.CreateModel(
            name='Langue',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('desc', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PJ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, null=True)),
                ('force', models.IntegerField(blank=True, null=True)),
                ('constitution', models.IntegerField(blank=True, null=True)),
                ('dexterite', models.IntegerField(blank=True, null=True)),
                ('intelligence', models.IntegerField(blank=True, null=True)),
                ('sagesse', models.IntegerField(blank=True, null=True)),
                ('charisme', models.IntegerField(blank=True, null=True)),
                ('classe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='PJs', to='data.classe')),
                ('historique', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='PJs', to='data.historique')),
                ('maitrise_competences', models.ManyToManyField(to='data.competence')),
            ],
        ),
        migrations.CreateModel(
            name='ProprieteArme',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('desc', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RaceCapacite',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('desc', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Armure',
            fields=[
                ('equipement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='data.equipement')),
                ('CA', models.IntegerField(blank=True, null=True)),
                ('mod_dext', models.IntegerField(blank=True, choices=[(1, 'mod.dex'), (2, 'mod.dex(+2max)'), (None, 'aucun')], null=True)),
                ('discretion_desavantage', models.BooleanField(default=False)),
                ('force_min', models.IntegerField(blank=True, null=True)),
                ('categorie', models.CharField(choices=[('LGR', 'Légère'), ('INT', 'Intermédiaire'), ('LRD', 'Lourde'), ('BCL', 'Bouclier')], max_length=3)),
            ],
            bases=('data.equipement',),
        ),
        migrations.CreateModel(
            name='Outil',
            fields=[
                ('equipement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='data.equipement')),
                ('type', models.CharField(choices=[('INS', 'Instrument de musique'), ('JEU', 'jeu'), ('KIT', 'kit'), ('OUT', "outils d'artisan"), ('VEH', 'vehicule')], default='OUT', max_length=3)),
            ],
            bases=('data.equipement',),
        ),
        migrations.CreateModel(
            name='ValeurCaracteristique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valeur', models.IntegerField(default=10)),
                ('PJ', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='valeur_caract', to='data.pj')),
                ('caracteristique', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='valeur_caract', to='data.caracteristique')),
            ],
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('desc', models.TextField(blank=True, null=True)),
                ('taille_max', models.IntegerField(blank=True, null=True)),
                ('taille_min', models.IntegerField(blank=True, null=True)),
                ('vitesse', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('famille', models.CharField(blank=True, max_length=20, null=True)),
                ('bonus_caracteristique', models.ManyToManyField(through='data.BonusCaracteristique', to='data.caracteristique')),
                ('capacite', models.ManyToManyField(to='data.racecapacite')),
            ],
        ),
        migrations.CreateModel(
            name='QuantiteEquipement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.IntegerField(default=1)),
                ('equipement', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quantite_equipement', to='data.equipement')),
                ('historique', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quantite_equipement', to='data.historique')),
            ],
        ),
        migrations.AddField(
            model_name='pj',
            name='race',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='PJs', to='data.race'),
        ),
        migrations.CreateModel(
            name='NbChoix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valeur', models.IntegerField(default=1)),
                ('choix', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valeur', to='data.choix')),
                ('historique', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='data.historique')),
            ],
        ),
        migrations.AddField(
            model_name='historique',
            name='langue',
            field=models.ManyToManyField(to='data.langue'),
        ),
        migrations.AddField(
            model_name='classe',
            name='choix_competences',
            field=models.ManyToManyField(related_name='classes', to='data.competence'),
        ),
        migrations.AddField(
            model_name='classe',
            name='jets_sauvegarde',
            field=models.ManyToManyField(to='data.caracteristique'),
        ),
        migrations.AddField(
            model_name='bonuscaracteristique',
            name='caracteristique',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bonus_caract', to='data.caracteristique'),
        ),
        migrations.AddField(
            model_name='bonuscaracteristique',
            name='race',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bonus_caract', to='data.race'),
        ),
        migrations.AddField(
            model_name='historique',
            name='maitrise',
            field=models.ManyToManyField(to='data.outil'),
        ),
        migrations.CreateModel(
            name='Arme',
            fields=[
                ('equipement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='data.equipement')),
                ('degat', models.CharField(blank=True, max_length=5, null=True)),
                ('type_degat', models.CharField(blank=True, choices=[('CTD', 'Contondant'), ('PRF', 'Cerforant'), ('TRC', 'Tranchant'), (None, '(Aucun)')], max_length=3, null=True)),
                ('portee_min', models.FloatField(blank=True, null=True)),
                ('portee_max', models.FloatField(blank=True, null=True)),
                ('propriete', models.ManyToManyField(to='data.proprietearme')),
            ],
            bases=('data.equipement',),
        ),
    ]
