# Generated by Django 4.1.3 on 2022-12-01 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='niveauxclasse',
            name='niveaux',
            field=models.ManyToManyField(blank=True, related_name='niveaux_classe', to='data.niveau'),
        ),
    ]
