# Generated by Django 4.1.3 on 2022-12-02 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_alter_niveauxclasse_niveaux'),
    ]

    operations = [
        migrations.AddField(
            model_name='historique',
            name='monaie_depart',
            field=models.ManyToManyField(blank=True, through='data.QuantiteMonaie', to='data.monaie'),
        ),
        migrations.AddField(
            model_name='quantitemonaie',
            name='historique',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data.historique'),
        ),
    ]
