# Generated by Django 4.1.3 on 2022-12-05 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_historique_monaie_depart_quantitemonaie_historique'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipement',
            old_name='prix',
            new_name='prix_objet',
        ),
        migrations.AlterField(
            model_name='historique',
            name='monaie_depart',
            field=models.ManyToManyField(blank=True, related_name='monaie', through='data.QuantiteMonaie', to='data.monaie'),
        ),
        migrations.AlterField(
            model_name='quantitemonaie',
            name='equipement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prix', to='data.equipement'),
        ),
        migrations.AlterField(
            model_name='quantitemonaie',
            name='historique',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='monaie_de_depart', to='data.historique'),
        ),
    ]
