# Generated by Django 4.1.3 on 2022-12-05 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_rename_prix_equipement_prix_objet_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='arme',
            name='degat_distance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='degat_distance', to='data.degat'),
        ),
        migrations.AlterField(
            model_name='equipement',
            name='poids',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
    ]
