# Generated by Django 4.1.3 on 2022-12-05 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_arme_degat_distance_alter_equipement_poids'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arme',
            name='portee',
        ),
        migrations.AddField(
            model_name='arme',
            name='portee',
            field=models.ManyToManyField(blank=True, to='data.portee'),
        ),
    ]
