# Generated by Django 4.1.3 on 2022-12-06 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0007_rename_categorie_portee_arme_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipement',
            name='url',
        ),
        migrations.AddField(
            model_name='classearmure',
            name='bonus_CA',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='quantitemonaie',
            name='monaie',
            field=models.ForeignKey(default='Po', null=True, on_delete=django.db.models.deletion.CASCADE, to='data.monaie'),
        ),
    ]
