# Generated by Django 4.1.3 on 2022-12-06 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0008_remove_equipement_url_classearmure_bonus_ca_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='armure',
            old_name='classeArmure',
            new_name='classe_armure',
        ),
    ]
