# Generated by Django 4.1.3 on 2022-12-06 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0009_rename_classearmure_armure_classe_armure'),
    ]

    operations = [
        migrations.RenameField(
            model_name='armure',
            old_name='classe_armure',
            new_name='CA',
        ),
    ]
