# Generated by Django 4.1.3 on 2022-12-06 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0010_rename_classe_armure_armure_ca'),
    ]

    operations = [
        migrations.RenameField(
            model_name='armure',
            old_name='categorie',
            new_name='categorie_armure',
        ),
    ]
