# Generated by Django 4.1.3 on 2022-12-06 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0011_rename_categorie_armure_categorie_armure'),
    ]

    operations = [
        migrations.RenameField(
            model_name='arme',
            old_name='categorie',
            new_name='categorie_arme',
        ),
        migrations.AlterField(
            model_name='armure',
            name='categorie_armure',
            field=models.CharField(blank=True, choices=[('légères', 'Armure légère'), ('intermédiaires', 'Armure intermédiaire'), ('lourdes', 'Armure lourde'), ('bouclier', 'bouclier')], max_length=50, null=True, verbose_name="categorie d'armure"),
        ),
    ]
