# Generated by Django 4.1.3 on 2022-12-06 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0012_rename_categorie_arme_categorie_arme_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EquipementAventurier',
        ),
    ]
