# Generated by Django 4.1.3 on 2022-12-06 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0015_remove_kit_equipement_ptr_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipement',
            name='poids',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True),
        ),
    ]
