# Generated by Django 4.1.3 on 2022-12-07 05:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0016_alter_equipement_poids'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maitrise',
            name='url',
        ),
        migrations.RemoveField(
            model_name='race',
            name='url',
        ),
        migrations.AddField(
            model_name='maitrise',
            name='ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data.equipement'),
        ),
    ]
