# Generated by Django 4.1.3 on 2022-12-07 05:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0017_remove_maitrise_url_remove_race_url_maitrise_ref'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maitrise',
            old_name='ref',
            new_name='ref_equip',
        ),
        migrations.AddField(
            model_name='maitrise',
            name='ref_comp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data.competence'),
        ),
    ]
