# Generated by Django 4.1.3 on 2022-12-07 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0018_rename_ref_maitrise_ref_equip_maitrise_ref_comp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sousrace',
            name='bonus_caracteristique',
        ),
        migrations.RemoveField(
            model_name='sousrace',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='sousrace',
            name='index',
        ),
        migrations.RemoveField(
            model_name='sousrace',
            name='langues',
        ),
        migrations.RemoveField(
            model_name='sousrace',
            name='maitrises_depart',
        ),
        migrations.RemoveField(
            model_name='sousrace',
            name='nom',
        ),
        migrations.RemoveField(
            model_name='sousrace',
            name='traits',
        ),
        migrations.RemoveField(
            model_name='sousrace',
            name='url',
        ),
        migrations.RemoveField(
            model_name='valeurcaracteristique',
            name='sous_race',
        ),
        migrations.AddField(
            model_name='race',
            name='langues_option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='race', to='data.optionslangue'),
        ),
        migrations.AddField(
            model_name='race',
            name='sorts',
            field=models.ManyToManyField(blank=True, related_name='race', to='data.sort'),
        ),
        migrations.AddField(
            model_name='sousrace',
            name='race_ptr',
            field=models.OneToOneField(auto_created=True, default=None, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='data.race'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sousrace',
            name='race',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sous_race', to='data.race'),
        ),
        migrations.CreateModel(
            name='OptionsSort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=50, null=True)),
                ('desc', models.TextField(blank=True, null=True)),
                ('nb', models.IntegerField(default=1, verbose_name='nombre de choix')),
                ('options', models.ManyToManyField(blank=True, to='data.sort')),
            ],
        ),
        migrations.AddField(
            model_name='race',
            name='sorts_option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='race', to='data.optionssort'),
        ),
    ]
