# Generated by Django 4.1.3 on 2022-12-07 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0020_remove_composante_name_composante_desc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='composante',
            name='Abreviation',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
