# Generated by Django 4.1.3 on 2022-12-07 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0022_rename_abreviation_composante_abreviation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sort',
            name='composante_desc',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
    ]
