# Generated by Django 4.1.3 on 2022-12-07 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0023_sort_composante_desc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sort',
            name='url',
        ),
        migrations.AlterField(
            model_name='cible',
            name='rayon',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='sort',
            name='composante_desc',
            field=models.TextField(blank=True, null=True, verbose_name='composantes description'),
        ),
    ]
