# Generated by Django 4.1.3 on 2022-12-07 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0024_remove_sort_url_alter_cible_rayon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sort',
            name='jet_attaque',
            field=models.CharField(choices=[('cac', 'corps à corps'), ('dist', 'distance'), (None, 'aucune')], default=None, max_length=50, null=True, verbose_name="categorie d'armure"),
        ),
    ]
