# Generated by Django 4.1.3 on 2022-12-07 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0025_sort_jet_attaque'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sort',
            name='jet_attaque',
            field=models.CharField(blank=True, choices=[('cac', 'corps à corps'), ('dist', 'distance'), (None, 'aucune')], default=None, max_length=50, null=True, verbose_name="jets d'attaque"),
        ),
        migrations.AlterField(
            model_name='sousrace',
            name='race',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sous_race', to='data.race'),
        ),
    ]
