# Generated by Django 4.1.3 on 2022-12-07 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0026_alter_sort_jet_attaque_alter_sousrace_race'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='age',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='race',
            name='poids',
            field=models.TextField(blank=True, null=True),
        ),
    ]
