# Generated by Django 4.1.3 on 2022-12-07 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0027_race_age_race_poids'),
    ]

    operations = [
        migrations.CreateModel(
            name='OptionsCaracteristique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=50, null=True)),
                ('desc', models.TextField(blank=True, null=True)),
                ('nb', models.IntegerField(default=1, verbose_name='nombre de choix')),
                ('options', models.ManyToManyField(blank=True, to='data.caracteristique')),
            ],
        ),
        migrations.AddField(
            model_name='race',
            name='bonus_caracteristique_option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='race', to='data.optionscaracteristique'),
        ),
    ]
