# Generated by Django 4.1.3 on 2022-12-07 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0028_optionscaracteristique_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='capacite',
            name='url',
        ),
        migrations.RemoveField(
            model_name='capacitemonstre',
            name='url',
        ),
        migrations.RemoveField(
            model_name='caracteristique',
            name='url',
        ),
        migrations.RemoveField(
            model_name='classe',
            name='url',
        ),
        migrations.RemoveField(
            model_name='competence',
            name='url',
        ),
        migrations.RemoveField(
            model_name='don',
            name='url',
        ),
        migrations.RemoveField(
            model_name='ecolemagie',
            name='url',
        ),
        migrations.RemoveField(
            model_name='etat',
            name='url',
        ),
        migrations.RemoveField(
            model_name='incantation',
            name='url',
        ),
        migrations.RemoveField(
            model_name='langue',
            name='url',
        ),
        migrations.RemoveField(
            model_name='monstre',
            name='url',
        ),
        migrations.RemoveField(
            model_name='niveauxclasse',
            name='url',
        ),
        
        migrations.RemoveField(
            model_name='proprietearme',
            name='url',
        ),
        migrations.RemoveField(
            model_name='regle',
            name='url',
        ),
        migrations.RemoveField(
            model_name='reglesoussection',
            name='url',
        ),
        migrations.RemoveField(
            model_name='sousclasse',
            name='url',
        ),
        migrations.RemoveField(
            model_name='sousclasse',
            name='url_niveau',
        ),
        migrations.RemoveField(
            model_name='trait',
            name='url',
        ),
        migrations.RemoveField(
            model_name='typedegat',
            name='url',
        ),
        migrations.AddField(
            model_name='race',
            name='parent_race',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='optionscaracteristique',
            name='options',
            field=models.ManyToManyField(blank=True, related_name='caracteristique', to='data.caracteristique'),
        ),
        
    ]
