# Generated by Django 4.1.3 on 2022-12-07 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0031_rename_capacité_vehicule_capacite_and_more'),
    ]

    operations = [

        migrations.AlterField(
            model_name='valeurcaracteristique',
            name='race',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='caracteristique', to='data.race'),
        ),
    ]
