# Generated by Django 4.1.3 on 2022-12-07 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0032_alter_optionscaracteristique_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='race',
            name='bonus_caracteristique_option',
        ),
        migrations.DeleteModel(
            name='OptionsCaracteristique',
        ),
    ]
