# Generated by Django 4.1.3 on 2022-12-07 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0034_optionscaracteristique_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classe',
            name='options_competences',
        ),
        migrations.DeleteModel(
            name='OptionsCompetence',
        ),
    ]
