# Generated by Django 4.1.3 on 2022-12-07 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0035_remove_classe_options_competences_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OptionsCompetence',
            fields=[
                ('type', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('desc', models.TextField(blank=True, null=True)),
                ('nb', models.IntegerField(default=1, verbose_name='nombre de choix')),
                ('options', models.ManyToManyField(blank=True, to='data.competence')),
            ],
        ),
        migrations.AddField(
            model_name='classe',
            name='options_competences',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='classe', to='data.optionscompetence'),
        ),
    ]
