# Generated by Django 4.1.3 on 2022-12-08 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0037_remove_race_sorts_option_delete_optionssort'),
    ]

    operations = [
        migrations.CreateModel(
            name='OptionsSort',
            fields=[
                ('nom', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('desc', models.TextField(blank=True, null=True)),
                ('nb', models.IntegerField(default=1, verbose_name='nombre de choix')),
                ('options', models.ManyToManyField(blank=True, to='data.sort')),
            ],
        ),
        migrations.AddField(
            model_name='race',
            name='sorts_option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='race', to='data.optionssort'),
        ),
    ]
