# Generated by Django 4.1.3 on 2022-12-08 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0038_optionssort_race_sorts_option'),
    ]

    operations = [
        migrations.RenameField(
            model_name='optionslangue',
            old_name='nb',
            new_name='nombre_choix',
        ),
    ]
