# Generated by Django 4.1.3 on 2022-12-08 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0039_rename_nb_optionslangue_nombre_choix'),
    ]

    operations = [
        migrations.RenameField(
            model_name='optionslangue',
            old_name='options',
            new_name='parmis',
        ),
    ]
