# Generated by Django 4.1.3 on 2022-12-08 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0041_rename_nb_optionscaracteristique_nombre_choix_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='optionscaracteristique',
            old_name='options',
            new_name='parmis',
        ),
        migrations.RenameField(
            model_name='optionscompetence',
            old_name='options',
            new_name='parmis',
        ),
        migrations.RenameField(
            model_name='optionsequipement',
            old_name='options',
            new_name='parmis',
        ),
        migrations.RenameField(
            model_name='optionsmaitrise',
            old_name='options',
            new_name='parmis',
        ),
        migrations.RenameField(
            model_name='optionssort',
            old_name='options',
            new_name='parmis',
        ),
    ]
