# Generated by Django 4.1.3 on 2022-12-08 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0042_rename_options_optionscaracteristique_parmis_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sort',
            name='jet_attaque',
            field=models.CharField(blank=True, choices=[('cac', 'corps à corps'), ('distance', 'distance'), (None, 'aucune')], default=None, max_length=50, null=True, verbose_name="jets d'attaque"),
        ),
    ]
