# Generated by Django 4.1.3 on 2022-12-08 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0043_alter_sort_jet_attaque'),
    ]


