# Generated by Django 4.1.3 on 2022-12-08 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0044_rename_capacité_vehicule_capacite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicule',
            name='capacité',
        ),
    ]
