# Generated by Django 4.1.3 on 2022-12-08 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0045_remove_vehicule_capacité'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicule',
            name='capacite',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
