# Generated by Django 4.1.3 on 2022-12-08 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0047_remove_sort_cible_remove_sort_degats_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sort',
            name='niveaux_superieurs',
            field=models.TextField(blank=True, null=True, verbose_name='description aux niveaux supèrieur'),
        ),
        migrations.AddField(
            model_name='sort',
            name='portee',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='portée du sort'),
        ),
        migrations.AddField(
            model_name='sort',
            name='reussite_JdS',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='réussite JdS'),
        ),
        migrations.AddField(
            model_name='sort',
            name='temps_incantation',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='durée du sort'),
        ),
    ]
