# Generated by Django 4.1.3 on 2022-12-08 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0048_sort_niveaux_superieurs_sort_portee_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Periode',
        ),
    ]
