# Generated by Django 4.1.3 on 2022-12-08 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0049_delete_periode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='degatsort',
            name='JdS_condition',
        ),
    ]
