# Generated by Django 4.1.3 on 2022-12-08 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0051_remove_degatsort_par_niveau'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DegatSort',
        ),
    ]
