# Generated by Django 4.1.3 on 2022-12-08 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0052_delete_degatsort'),
    ]

    operations = [
        migrations.CreateModel(
            name='DegatSort',
            fields=[
                ('degat_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='data.degat')),
                ('desc', models.TextField(blank=True, null=True)),
                ('emplacement_nv1', models.ManyToManyField(blank=True, related_name='emplacement_nv1', to='data.degat')),
                ('emplacement_nv2', models.ManyToManyField(blank=True, related_name='emplacement_nv2', to='data.degat')),
                ('emplacement_nv3', models.ManyToManyField(blank=True, related_name='emplacement_nv3', to='data.degat')),
                ('emplacement_nv4', models.ManyToManyField(blank=True, related_name='emplacement_nv4', to='data.degat')),
                ('emplacement_nv5', models.ManyToManyField(blank=True, related_name='emplacement_nv5', to='data.degat')),
                ('emplacement_nv6', models.ManyToManyField(blank=True, related_name='emplacement_nv6', to='data.degat')),
                ('emplacement_nv7', models.ManyToManyField(blank=True, related_name='emplacement_nv7', to='data.degat')),
                ('emplacement_nv8', models.ManyToManyField(blank=True, related_name='emplacement_nv8', to='data.degat')),
                ('emplacement_nv9', models.ManyToManyField(blank=True, related_name='emplacement_nv9', to='data.degat')),
            ],
            bases=('data.degat',),
        ),
    ]
