# Generated by Django 4.1.3 on 2022-12-08 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0054_sort_degats'),
    ]

    operations = [
        migrations.AddField(
            model_name='sort',
            name='duree',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='durée du sort'),
        ),
        migrations.AlterField(
            model_name='sort',
            name='temps_incantation',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name="temps d'incantation"),
        ),
    ]
