# Generated by Django 4.1.3 on 2022-12-08 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0055_sort_duree_alter_sort_temps_incantation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sort',
            name='degats',
        ),
        migrations.DeleteModel(
            name='DegatSort',
        ),
    ]
