# Generated by Django 4.1.3 on 2022-12-08 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0058_degatsort_emplacement_nv0'),
    ]

    operations = [
        migrations.CreateModel(
            name='Soin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bonus', models.IntegerField(default=0)),
                ('bonus_mod', models.BooleanField(default=False)),
                ('de', models.CharField(default='1d6', max_length=50, verbose_name='dé de dégat')),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data.typedegat')),
            ],
        ),
        migrations.RenameModel(
            old_name='DegatSort',
            new_name='DegatSortEmplacements',
        ),
        migrations.RenameField(
            model_name='sort',
            old_name='degats',
            new_name='degats_par_emplacement',
        ),
        migrations.CreateModel(
            name='SoinSortEmplacements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.TextField(blank=True, null=True)),
                ('emplacement_nv0', models.ManyToManyField(blank=True, related_name='emplacement_nv0', to='data.soin')),
                ('emplacement_nv1', models.ManyToManyField(blank=True, related_name='emplacement_nv1', to='data.soin')),
                ('emplacement_nv2', models.ManyToManyField(blank=True, related_name='emplacement_nv2', to='data.soin')),
                ('emplacement_nv3', models.ManyToManyField(blank=True, related_name='emplacement_nv3', to='data.soin')),
                ('emplacement_nv4', models.ManyToManyField(blank=True, related_name='emplacement_nv4', to='data.soin')),
                ('emplacement_nv5', models.ManyToManyField(blank=True, related_name='emplacement_nv5', to='data.soin')),
                ('emplacement_nv6', models.ManyToManyField(blank=True, related_name='emplacement_nv6', to='data.soin')),
                ('emplacement_nv7', models.ManyToManyField(blank=True, related_name='emplacement_nv7', to='data.soin')),
                ('emplacement_nv8', models.ManyToManyField(blank=True, related_name='emplacement_nv8', to='data.soin')),
                ('emplacement_nv9', models.ManyToManyField(blank=True, related_name='emplacement_nv9', to='data.soin')),
            ],
        ),
        migrations.CreateModel(
            name='DegatSortNiveaux',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.TextField(blank=True, null=True)),
                ('niveau_0', models.ManyToManyField(blank=True, related_name='niveau_0', to='data.degat')),
                ('niveau_1', models.ManyToManyField(blank=True, related_name='niveau_1', to='data.degat')),
                ('niveau_2', models.ManyToManyField(blank=True, related_name='niveau_2', to='data.degat')),
                ('niveau_3', models.ManyToManyField(blank=True, related_name='niveau_3', to='data.degat')),
                ('niveau_4', models.ManyToManyField(blank=True, related_name='niveau_4', to='data.degat')),
                ('niveau_5', models.ManyToManyField(blank=True, related_name='niveau_5', to='data.degat')),
                ('niveau_6', models.ManyToManyField(blank=True, related_name='niveau_6', to='data.degat')),
                ('niveau_7', models.ManyToManyField(blank=True, related_name='niveau_7', to='data.degat')),
                ('niveau_8', models.ManyToManyField(blank=True, related_name='niveau_8', to='data.degat')),
                ('niveau_9', models.ManyToManyField(blank=True, related_name='niveau_9', to='data.degat')),
            ],
        ),
        migrations.AddField(
            model_name='sort',
            name='degats_par_niveaux',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data.degatsortniveaux'),
        ),
        migrations.AddField(
            model_name='sort',
            name='soins_par_emplacement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data.soinsortemplacements'),
        ),
    ]
