# Generated by Django 4.1.3 on 2022-12-09 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0062_arme_categorie_arme_arme_categorie_arme_portee_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='armure',
            name='categorie_armure',
        ),
    ]
