# Generated by Django 4.1.3 on 2022-12-09 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0063_remove_armure_categorie_armure'),
    ]

    operations = [
        migrations.AddField(
            model_name='armure',
            name='categorie_armure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categorie_armure', to='data.categorieequipement'),
        ),
    ]
