# Generated by Django 4.1.3 on 2022-12-09 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0064_armure_categorie_armure'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='optionscompetence',
            name='parmis',
        ),
        migrations.RemoveField(
            model_name='optionsequipement',
            name='parmis',
        ),
        migrations.RemoveField(
            model_name='optionslangue',
            name='parmis',
        ),
        migrations.RemoveField(
            model_name='optionsmaitrise',
            name='parmis',
        ),
        migrations.RemoveField(
            model_name='optionssort',
            name='parmis',
        ),
        migrations.RemoveField(
            model_name='classe',
            name='equipements_options',
        ),
        migrations.RemoveField(
            model_name='classe',
            name='options_competences',
        ),
        migrations.RemoveField(
            model_name='classe',
            name='options_maitrises',
        ),
        migrations.RemoveField(
            model_name='historique',
            name='equipements_options',
        ),
        migrations.RemoveField(
            model_name='historique',
            name='langues_options',
        ),
        migrations.RemoveField(
            model_name='historique',
            name='maitrises_options',
        ),
        migrations.RemoveField(
            model_name='race',
            name='bonus_caracteristique_option',
        ),
        migrations.RemoveField(
            model_name='race',
            name='langues_option',
        ),
        migrations.RemoveField(
            model_name='race',
            name='maitrises_option',
        ),
        migrations.RemoveField(
            model_name='race',
            name='sorts_option',
        ),
        migrations.DeleteModel(
            name='OptionsCaracteristique',
        ),
        migrations.DeleteModel(
            name='OptionsCompetence',
        ),
        migrations.DeleteModel(
            name='OptionsEquipement',
        ),
        migrations.DeleteModel(
            name='OptionsLangue',
        ),
        migrations.DeleteModel(
            name='OptionsMaitrise',
        ),
        migrations.DeleteModel(
            name='OptionsSort',
        ),
    ]
