# Generated by Django 4.1.3 on 2022-12-09 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0066_option'),
    ]

    operations = [
        migrations.AddField(
            model_name='classe',
            name='equipements_options',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='classe_equipements', to='data.option'),
        ),
        migrations.AddField(
            model_name='classe',
            name='options_competences',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='classe_competences', to='data.option'),
        ),
        migrations.AddField(
            model_name='classe',
            name='options_maitrises',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='classe_maitrises', to='data.option'),
        ),
    ]
