# Generated by Django 4.1.3 on 2022-12-09 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0067_classe_equipements_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historique',
            name='equipements_options',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='historique_equipements', to='data.option'),
        ),
        migrations.AddField(
            model_name='historique',
            name='langues_options',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='historique_langues', to='data.option'),
        ),
        migrations.AddField(
            model_name='historique',
            name='maitrises_options',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='historique_maitrises', to='data.option'),
        ),
    ]
