# Generated by Django 4.1.3 on 2022-12-09 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0068_historique_equipements_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='bonus_caracteristique_option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='race_caracteristiques', to='data.option'),
        ),
        migrations.AddField(
            model_name='race',
            name='langues_option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='race_langues', to='data.option'),
        ),
        migrations.AddField(
            model_name='race',
            name='maitrises_option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='race_maitrises', to='data.option'),
        ),
        migrations.AddField(
            model_name='race',
            name='sorts_option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='race_sorts', to='data.option'),
        ),
    ]
