# Generated by Django 4.1.3 on 2022-12-09 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0069_race_bonus_caracteristique_option_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actionmonstre',
            options={'ordering': ['index']},
        ),
        migrations.AlterModelOptions(
            name='alignement',
            options={'ordering': ['index']},
        ),
        migrations.AlterModelOptions(
            name='arme',
            options={'ordering': ['index']},
        ),
        migrations.AlterModelOptions(
            name='armure',
            options={'ordering': ['index']},
        ),
        migrations.AlterModelOptions(
            name='capacite',
            options={'ordering': ['index']},
        ),
        migrations.AlterModelOptions(
            name='capacitemonstre',
            options={'ordering': ['index']},
        ),
        migrations.AlterModelOptions(
            name='caracteristique',
            options={'ordering': ['index']},
        ),
        migrations.AlterModelOptions(
            name='categorieequipement',
            options={'ordering': ['index']},
        ),
        migrations.AlterModelOptions(
            name='classe',
            options={'ordering': ['index']},
        ),
        migrations.AlterModelOptions(
            name='competence',
            options={'ordering': ['index']},
        ),
        migrations.AlterModelOptions(
            name='composante',
            options={'ordering': ['index']},
        ),
        migrations.AlterModelOptions(
            name='don',
            options={'ordering': ['index']},
        ),
        migrations.AlterModelOptions(
            name='ecolemagie',
            options={'ordering': ['index']},
        ),
        migrations.AlterModelOptions(
            name='epuisement',
            options={'ordering': ['index']},
        ),
        migrations.AlterModelOptions(
            name='equipement',
            options={'ordering': ['index']},
        ),
        migrations.AlterModelOptions(
            name='etat',
            options={'ordering': ['index']},
        ),
        migrations.AlterModelOptions(
            name='historique',
            options={'ordering': ['index']},
        ),
        migrations.AlterModelOptions(
            name='info',
            options={'ordering': ['index']},
        ),
        migrations.AlterModelOptions(
            name='langue',
            options={'ordering': ['index']},
        ),
        migrations.AlterModelOptions(
            name='maitrise',
            options={'ordering': ['index']},
        ),
        migrations.AlterModelOptions(
            name='monstre',
            options={'ordering': ['index']},
        ),
        migrations.AlterModelOptions(
            name='niveau',
            options={'ordering': ['index']},
        ),
        migrations.AlterModelOptions(
            name='niveauxclasse',
            options={'ordering': ['index']},
        ),
        migrations.AlterModelOptions(
            name='option',
            options={'ordering': ['index']},
        ),
        migrations.AlterModelOptions(
            name='packequipement',
            options={'ordering': ['index']},
        ),
        migrations.AlterModelOptions(
            name='proprietearme',
            options={'ordering': ['index']},
        ),
        migrations.AlterModelOptions(
            name='race',
            options={'ordering': ['index']},
        ),
        migrations.AlterModelOptions(
            name='regle',
            options={'ordering': ['index']},
        ),
        migrations.AlterModelOptions(
            name='reglesoussection',
            options={'ordering': ['index']},
        ),
        migrations.AlterModelOptions(
            name='sensmonstre',
            options={'ordering': ['index']},
        ),
        migrations.AlterModelOptions(
            name='sort',
            options={'ordering': ['index']},
        ),
        migrations.AlterModelOptions(
            name='sousclasse',
            options={'ordering': ['index']},
        ),
        migrations.AlterModelOptions(
            name='sousrace',
            options={'ordering': ['index']},
        ),
        migrations.AlterModelOptions(
            name='taille',
            options={'ordering': ['index']},
        ),
        migrations.AlterModelOptions(
            name='trait',
            options={'ordering': ['index']},
        ),
        migrations.AlterModelOptions(
            name='typedegat',
            options={'ordering': ['index']},
        ),
        migrations.AlterModelOptions(
            name='vehicule',
            options={'ordering': ['index']},
        ),
        migrations.AlterField(
            model_name='arme',
            name='categorie_arme_portee',
            field=models.ForeignKey(default='arme-de-guerre-de-corps-a-corps', on_delete=django.db.models.deletion.CASCADE, related_name='categorie_arme_portee', to='data.categorieequipement'),
        ),
    ]
