# Generated by Django 4.1.3 on 2022-12-09 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0070_alter_actionmonstre_options_alter_alignement_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PackEquipement',
        ),
    ]
