# Generated by Django 4.1.3 on 2022-12-10 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0072_packequipement_quantiteequipement_pack_equipement_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quantiteequipement',
            name='pack_equipement',
        ),
        migrations.RemoveField(
            model_name='quantitemonaie',
            name='pack_equipement',
        ),
        migrations.DeleteModel(
            name='PackEquipement',
        ),
    ]
