# Generated by Django 4.1.3 on 2022-12-10 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0073_remove_quantiteequipement_pack_equipement_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipementAventurier',
            fields=[
                ('equipement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='data.equipement')),
                ('categorie_equipement_aventurier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data.categorieequipement')),
            ],
            options={
                'ordering': ['index'],
                'abstract': False,
            },
            bases=('data.equipement',),
        ),
    ]
