# Generated by Django 4.1.3 on 2022-12-10 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0074_equipementaventurier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipement',
            name='categorie_equipement',
            field=models.ForeignKey(default='equipement-daventurier', on_delete=django.db.models.deletion.CASCADE, to='data.categorieequipement'),
        ),
    ]
