# Generated by Django 4.1.3 on 2022-12-10 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0075_alter_equipement_categorie_equipement'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuantiteEquipementAventurier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.IntegerField(default=1)),
                ('equipement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quantite_equipement_aventurier', to='data.equipementaventurier')),
            ],
        ),
        migrations.CreateModel(
            name='Sac',
            fields=[
                ('equipement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='data.equipement')),
                ('contenu', models.ManyToManyField(blank=True, related_name='sac', through='data.QuantiteEquipementAventurier', to='data.equipementaventurier')),
            ],
            options={
                'ordering': ['index'],
                'abstract': False,
            },
            bases=('data.equipement',),
        ),
        migrations.AddField(
            model_name='quantiteequipementaventurier',
            name='sac',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quantite_equipement_aventurier', to='data.sac'),
        ),
    ]
