# Generated by Django 4.1.3 on 2022-12-10 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0076_quantiteequipementaventurier_sac_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipementaventurier',
            name='categorie_equipement_aventurier',
            field=models.ForeignKey(default='equipement-standard', on_delete=django.db.models.deletion.CASCADE, to='data.categorieequipement'),
        ),
    ]
