# Generated by Django 4.1.3 on 2022-12-10 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0077_alter_equipementaventurier_categorie_equipement_aventurier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipement',
            name='categorie_equipement',
            field=models.ForeignKey(default='sac-dequipements', on_delete=django.db.models.deletion.CASCADE, to='data.categorieequipement'),
        ),
    ]
