# Generated by Django 4.1.3 on 2022-12-10 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0079_alter_equipement_categorie_equipement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipementaventurier',
            name='categorie_equipement_aventurier',
            field=models.ForeignKey(default='outil-dartisan', on_delete=django.db.models.deletion.CASCADE, to='data.categorieequipement'),
        ),
    ]
