# Generated by Django 4.1.3 on 2022-12-10 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0080_alter_equipementaventurier_categorie_equipement_aventurier'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackEquipementClasse',
            fields=[
                ('nom', models.CharField(max_length=50)),
                ('index', models.CharField(default='default', max_length=50, primary_key=True, serialize=False)),
                ('desc', models.TextField(blank=True, null=True, verbose_name='description')),
                ('contenu', models.ManyToManyField(blank=True, related_name='Pack', to='data.equipement')),
            ],
            options={
                'ordering': ['index'],
                'abstract': False,
            },
        ),
    ]
