# Generated by Django 4.1.3 on 2022-12-10 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0081_packequipementclasse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quantitemonaie',
            name='monaie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='data.monaie'),
        ),
        migrations.AlterField(
            model_name='quantitemonaie',
            name='quantite',
            field=models.IntegerField(),
        ),
    ]
