# Generated by Django 4.1.3 on 2022-12-10 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0085_alter_quantitemonaie_monaie'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PackEquipementClasse',
        ),
    ]
