# Generated by Django 4.1.3 on 2022-12-10 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0087_packequipementclasse_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='categorie_equipement',
            field=models.ManyToManyField(blank=True, related_name='categories_equipements', to='data.categorieequipement'),
        ),
        migrations.AddField(
            model_name='packequipementclasse',
            name='options',
            field=models.ManyToManyField(blank=True, related_name='Pack', to='data.option'),
        ),
    ]
