# Generated by Django 4.1.3 on 2022-12-10 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0088_option_categorie_equipement_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classe',
            name='equipements_options',
        ),
    ]
