# Generated by Django 4.1.3 on 2022-12-10 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0090_classe_equipements_options_option_pack_equipement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classe',
            name='url_niveau',
        ),
    ]
