# Generated by Django 4.1.3 on 2022-12-11 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0092_classe_niveaux'),
    ]

    operations = [
        migrations.RenameField(
            model_name='option',
            old_name='categorie_equipement',
            new_name='categories_equipements',
        ),
        migrations.RenameField(
            model_name='option',
            old_name='pack_equipement',
            new_name='packs_equipements',
        ),
        migrations.AlterField(
            model_name='quantiteequipement',
            name='equipement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quantite', to='data.equipement'),
        ),
        migrations.AlterField(
            model_name='quantiteequipement',
            name='pack_equipement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contenu_pack', to='data.packequipementclasse'),
        ),
    ]
