# Generated by Django 4.1.3 on 2022-12-11 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0093_rename_categorie_equipement_option_categories_equipements_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='capacite',
            name='classe',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='capacite', to='data.classe'),
        ),
        migrations.AddField(
            model_name='capacite',
            name='sous_classe',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='capacite', to='data.sousclasse'),
        ),
    ]
