# Generated by Django 4.1.3 on 2022-12-11 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0094_capacite_classe_capacite_sous_classe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capacite',
            name='classe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='capacite', to='data.classe'),
        ),
        migrations.AlterField(
            model_name='capacite',
            name='sous_classe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='capacite', to='data.sousclasse'),
        ),
    ]
