# Generated by Django 4.1.3 on 2022-12-11 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0095_alter_capacite_classe_alter_capacite_sous_classe'),
    ]

    operations = [
        migrations.AddField(
            model_name='incantation',
            name='nom',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
