# Generated by Django 4.1.3 on 2022-12-11 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0096_incantation_nom'),
    ]

    operations = [
        migrations.RenameField(
            model_name='incantation',
            old_name='Caracteristique',
            new_name='caracteristique',
        ),
    ]
