# Generated by Django 4.1.3 on 2022-12-12 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0097_rename_caracteristique_incantation_caracteristique'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='niveau',
            options={'ordering': ['classe', 'niveau']},
        ),
        migrations.AddField(
            model_name='quantitespecifique',
            name='valeur',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='classe',
            name='niveaux',
            field=models.ManyToManyField(blank=True, related_name='classe', to='data.niveau'),
        ),
        migrations.AlterField(
            model_name='quantitespecifique',
            name='niveau',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='specifique', to='data.niveau'),
        ),
    ]
