# Generated by Django 4.1.3 on 2022-12-12 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0098_alter_niveau_options_quantitespecifique_valeur_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quantitespecifique',
            name='quantite',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
