# Generated by Django 4.1.3 on 2022-12-12 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0099_alter_quantitespecifique_quantite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historique',
            name='url',
        ),
    ]
