# Generated by Django 4.1.3 on 2022-12-17 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0101_remove_alignement_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='capacites',
            field=models.ManyToManyField(blank=True, related_name='capacites_options', to='data.capacite'),
        ),
    ]
