# Generated by Django 4.1.3 on 2022-12-17 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0102_option_capacites'),
    ]

    operations = [
        migrations.AddField(
            model_name='capacite',
            name='option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data.option'),
        ),
    ]
